In [1]:
# Import torch and other required modules
import torch

In [8]:
# Create tensor for single number
t1 = torch.tensor(1.)
print(t1)
t1.dtype

tensor(1.)


torch.float32

In [9]:
t2 = torch.tensor(1)
print(t2)
t2.dtype

tensor(1)


torch.int64

In [10]:
t3 = torch.tensor(1.000)
print(t3)
t3.dtype

tensor(1.)


torch.float32

In [11]:
t4 = torch.tensor(1.012)
print(t4)
t4.dtype

tensor(1.0120)


torch.float32

In [18]:
t5 = torch.tensor(100)
print(t5)
t5.dtype
print(t5.shape)

tensor(100)
torch.Size([])


In [17]:
t6 = torch.tensor([1, 2, 3])
print(t6)
print(t6.dtype)
print(t6.shape)

tensor([1, 2, 3])
torch.int64
torch.Size([3])


In [19]:
t7 = torch.tensor([1., 2, 3., 4])
print(t7)
print(t7.dtype)
print(t7.shape)

tensor([1., 2., 3., 4.])
torch.float32
torch.Size([4])


In [21]:
t8 = torch.tensor([[1,2,3],[3,4,5],[4,5,6]])
print(t8)
print(t8.shape)

tensor([[1, 2, 3],
        [3, 4, 5],
        [4, 5, 6]])
torch.Size([3, 3])


In [22]:
t9 = torch.tensor([[[1,2,3],[2,3,4],[4,5,6]],[[1,2,3],[4,5,6],[7,8,9]]])
print(t9)
print(t9.shape)

tensor([[[1, 2, 3],
         [2, 3, 4],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
torch.Size([2, 3, 3])


In [24]:
t10 = torch.tensor(-5.1)
print(t10)
print(t10.dtype)

tensor(-5.1000)
torch.float32


In [30]:
x = torch.tensor(1)
y = torch.tensor(5)
z = torch.tensor(10)
x, y, z

(tensor(1), tensor(5), tensor(10))

In [31]:
sum = x + y + z
print('sum=', sum)

sum= tensor(16)


In [39]:
a = torch.tensor(5.)
b = torch.tensor(6., requires_grad = True)
c = torch.tensor(2., requires_grad = True)

In [40]:
d = a * b + c
d

tensor(32., grad_fn=<AddBackward0>)

In [41]:
d.backward()


In [42]:
print('dd/da =', a.grad)
print('dd/db =', b.grad)
print('dd/dc =', c.grad)

dd/da = None
dd/db = tensor(5.)
dd/dc = tensor(1.)


In [43]:
import numpy as np

In [44]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [45]:
#to convert into torch.tensor
y = torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]])

In [46]:
a1 = np.array([[1.,2,3.],[3,4.,5],[4,5,6]])
a1

array([[1., 2., 3.],
       [3., 4., 5.],
       [4., 5., 6.]])

In [48]:
b = torch.from_numpy(a1)
b

tensor([[1., 2., 3.],
        [3., 4., 5.],
        [4., 5., 6.]], dtype=torch.float64)

In [59]:
a2 = np.array([[1.,2,3],[3,5],[4,5,6]])
a2

array([list([1.0, 2, 3]), list([3, 5]), list([4, 5, 6])], dtype=object)

In [60]:
b2 = torch.from_numpy(a2)
b2

TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, int64, int32, int16, int8, uint8, and bool.

Error because of uneven dimension in a2

In [62]:
c1 = b.numpy()
c1

array([[1., 2., 3.],
       [3., 4., 5.],
       [4., 5., 6.]])

In [65]:
import jovian

In [ ]:
jovian.commit()