In [1]:
import torch

In [2]:
torch.linspace(5,60,steps=4,dtype=torch.int32)

tensor([ 5, 23, 41, 60], dtype=torch.int32)

In [3]:
torch.linspace(5,60,steps=3,dtype=torch.int32)

tensor([ 5, 32, 60], dtype=torch.int32)

In [4]:
torch.linspace(5,10,steps=1,dtype=torch.int32)

tensor([5], dtype=torch.int32)

In [5]:
torch.linspace(5,10,steps=5,dtype=torch.int32)

tensor([ 5,  6,  7,  8, 10], dtype=torch.int32)

In [6]:
torch.linspace(5,10,steps=6,dtype=torch.int32)

tensor([ 5,  6,  7,  8,  9, 10], dtype=torch.int32)

In [7]:
t1 = torch.tensor([.5, .2, .3, .6])
torch.log(t1)

tensor([-0.6931, -1.6094, -1.2040, -0.5108])

In [8]:
t2 = torch.tensor([5., 2., 3, 5])
torch.log(t2)

tensor([1.6094, 0.6931, 1.0986, 1.6094])

In [9]:
t3 = torch.randn((3,2))
print(t3)
torch.log(t3)

tensor([[-0.1820,  0.9666],
        [-0.0879, -0.0412],
        [ 1.5794,  0.5134]])


tensor([[    nan, -0.0339],
        [    nan,     nan],
        [ 0.4570, -0.6666]])

In [10]:
x = torch.randn((1,4))
print(x)
torch.mean(x)

tensor([[ 1.3566, -1.5073, -0.1588,  0.0673]])


tensor(-0.0605)

In [12]:
t4 = torch.tensor([1.,2.,3.,4.])
print(t4)
torch.mean(t4)

tensor([1., 2., 3., 4.])


tensor(2.5000)

In [13]:
y = torch.randn((3,4))
print(y)
torch.mean(x, dim=0)

tensor([[-0.1494,  0.1668,  0.4208,  0.5217],
        [-0.6127, -1.7369,  0.5749,  0.9718],
        [ 1.4454, -0.0701,  0.9250, -0.8554]])


tensor([ 1.3566, -1.5073, -0.1588,  0.0673])

In [17]:
x = torch.randn((1,12))
print(x)
torch.reshape(x,(3,4))

tensor([[-1.1498,  0.4862,  0.4823,  0.3004,  0.5534,  0.3671, -1.5319, -2.2067,
          0.0580,  2.0197, -0.9727, -0.1863]])


tensor([[-1.1498,  0.4862,  0.4823,  0.3004],
        [ 0.5534,  0.3671, -1.5319, -2.2067],
        [ 0.0580,  2.0197, -0.9727, -0.1863]])

In [23]:
x = torch.randn((8,2))
print(x)
torch.reshape(x, (2,8))

tensor([[-0.4857,  0.2053],
        [ 2.0759,  0.6173],
        [-0.0532,  0.6188],
        [-0.9812,  0.3671],
        [ 0.6012, -0.0860],
        [-0.5246, -0.4796],
        [-1.6124,  0.4524],
        [-0.1751, -1.4426]])


tensor([[-0.4857,  0.2053,  2.0759,  0.6173, -0.0532,  0.6188, -0.9812,  0.3671],
        [ 0.6012, -0.0860, -0.5246, -0.4796, -1.6124,  0.4524, -0.1751, -1.4426]])

In [24]:
x = torch.randn((3,4))
print(x)
torch.reshape(x,(6,2))

tensor([[ 1.2332, -0.3456,  0.8104,  0.8147],
        [-0.8788,  0.6571, -0.2464,  1.3996],
        [-0.3112, -1.5342,  0.3515,  0.8109]])


tensor([[ 1.2332, -0.3456],
        [ 0.8104,  0.8147],
        [-0.8788,  0.6571],
        [-0.2464,  1.3996],
        [-0.3112, -1.5342],
        [ 0.3515,  0.8109]])

In [25]:
x = torch.randn((3,4))
print(x)
torch.reshape(x,(4,4))

tensor([[ 0.8596,  0.8593,  0.7662, -0.2327],
        [ 0.0955, -0.5315, -0.2560,  0.5628],
        [-0.1221, -3.4375,  1.0008,  0.6501]])


RuntimeError: shape '[4, 4]' is invalid for input of size 12

In [26]:
x = torch.randn((3,5))
print(x)
torch.t(x)

tensor([[-0.8394, -0.0432, -0.2855, -1.4391, -2.0718],
        [-0.4532,  0.1112,  0.1172, -0.2167, -0.2202],
        [-1.0394,  0.6274,  0.0442,  2.5665, -0.7681]])


tensor([[-0.8394, -0.4532, -1.0394],
        [-0.0432,  0.1112,  0.6274],
        [-0.2855,  0.1172,  0.0442],
        [-1.4391, -0.2167,  2.5665],
        [-2.0718, -0.2202, -0.7681]])

In [28]:
x = torch.randn((3,5))
print(x)
torch.t(x)

tensor([[-0.0613, -0.6107,  1.0481, -0.8908, -0.7959],
        [-0.9821,  0.3009, -0.5735, -1.2812,  0.4730],
        [ 1.5150,  1.5470,  1.6009,  0.3884,  0.0868]])


tensor([[-0.0613, -0.9821,  1.5150],
        [-0.6107,  0.3009,  1.5470],
        [ 1.0481, -0.5735,  1.6009],
        [-0.8908, -1.2812,  0.3884],
        [-0.7959,  0.4730,  0.0868]])

In [29]:
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
y = torch.as_strided(x,(3,2),(3,1))
y

tensor([[1, 2],
        [4, 5],
        [7, 8]])

In [30]:
y = torch.as_strided(x,(2,3),(1,2))
y

tensor([[1, 3, 5],
        [2, 4, 6]])